name: Java CI

on:
  push:
    branches:
      - sprint_7-solution-in-file-manager
  pull_request:
    branches:
      - sprint_7-solution-in-file-manager

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  
        distribution: 'temurin'  
  